# Generated by Django 4.0.4 on 2022-10-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='book_tushu',
        ),
    ]
